#!/bin/zsh

ROOT=$(echo $0:A | sed -E 's/\/init\/.*//')
NAME=$(basename ${0})
INIT=${ROOT}/init

if [ ! -d ~/.oh-my-zsh ]; then
  ${INIT}/install-oh-my-zsh || { echo "Unable to bootstrap oh-my-zsh!" && exit -1 }
fi
TARGET=~/.oh-my-zsh/custom
if [ ! -d ${TARGET}/.git ]; then
  echo "OrganL oh-my-zsh theme is not installed."
  echo "Cloning OrganL theme (RW) to: ${TARGET}"
  git clone git@github.com:organl/oh-my-zsh-organl.git ${TARGET}
  if [ $? -ne 0 ]; then
    echo "Clone failed, trying fallback..."
    echo "Cloning OrganL theme (RO) to: ${TARGET}"
    git clone https://github.com/organl/oh-my-zsh-organl.git ${TARGET}
  fi
fi

